# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NEIN am 10. Juni - für ein BESSERES Geldspielgesetz!
email: contact@ein-besseres-geldspielgesetz.ch
description: > # this means to ignore newlines until "baseurl:"
  Mit einem NEIN zum Geldspielgesetz gewinnen ALLE!
  Alle ausser der Geldspiellobby!
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.ein-besseres-geldspielgesetz.ch" # the base hostname & protocol for your site
github_username:  geldspielgesetz

sass:
  sass_dir: assets/css
  style: :nested

# Build settings
markdown: kramdown
