-function(){"use strict";var g;var h={i:function(a,b){var c=h.c();c&&c.saveStyleOverride(this,a,b);this.style[a]=b},f:function(a,b){b?this.classList.add(a):this.classList.remove(a)},v:function(a){if("undefined"!=typeof a){var b=h.c();b&&b.saveInitialText(this);this.textContent=a;b&&b.applyStylePreservation(this)}},u:function(a){if("undefined"!=typeof a){var b=h.c();b&&b.saveInitialText(this);this.innerHTML=a;b&&b.applyStylePreservation(this)}},show:function(a){this.style.display=a?"":"none"},setAttribute:function(a,b){this.setAttribute(a,
b)},c:function(){return document.querySelector("gwd-text-helper")}};window.Binder=h;h.setText=h.v;h.setStyle=h.i;h.setHtml=h.u;h.addOrRemoveClassName=h.f;h.show=h.show;h.setAttribute=h.setAttribute;var l={limit:function(a,b){return b?a&&a.length&&("string"==typeof b&&(b=parseInt(b,10)),!isNaN(b))?a.slice(0,b):a:a},pluck:function(a,b){if(a){var c=b.split(".");return a.map(function(a){if(1==c.length)return a[c[0]];var b=a;c.forEach(function(a){b&&(b=b[a])});return b})}return[]},join:function(a,b){return a?a.join(b||","):""},s:function(a,b){return l.join(l.pluck(a,b))},toUpperCase:function(a){return a?a.toUpperCase():a},toLowerCase:function(a){return a?a.toLowerCase():a},A:function(a){if("undefined"!=
typeof a)return a+"px"},w:function(a){return a?a.replace(/0x/,"#"):a}};window.Formatter=l;l.limit=l.limit;l.toUpperCase=l.toUpperCase;l.toLowerCase=l.toLowerCase;l.toPixelValue=l.A;l.toHex=l.w;l.pluck=l.pluck;l.join=l.join;l.pluckAndJoin=l.s;var n=/^bind-/,p=/^style-/,q=/^class-/,r=/^each-/,t=/\/-([a-z])\/g/;function u(a){return String(a).replace(t,function(a,c){return c.toUpperCase()})}function w(a){return!(!a||!n.test(a.name))}function x(a){return!(!a||0!=a.name.indexOf("bind-each"))}function y(a){Array.prototype.slice.call(a.attributes).filter(x).forEach(function(b){a.removeAttribute(b.name)})}var z=function(){};goog.inherits(z,HTMLElement);g=z.prototype;
g.createdCallback=function(){this.a={text:"setText",html:"setHtml",show:"show"};this.b={limit:"limit",pixelvalue:"toPixelValue",uppercase:"toUpperCase",lowercase:"toLowerCase",hex:"toHex",pluck:"pluck",join:"join",pluckandjoin:"pluckAndJoin"};this.h=!1};g.getBinder=function(){return h};g.getFormatter=function(){return l};
g.bindData=function(a,b){b=b||Array.prototype.slice.call(document.querySelectorAll("*"));var c=document.querySelector("meta[name=environment]");this.h="gwd-adwords"==(c?c.getAttribute("content"):"");b.forEach(this.j.bind(this,a))};g.j=function(a,b){if(!b.hasAttribute("gwd-bind-each-template")){for(var c,e=Array.prototype.slice.call(b.attributes),f=e.length,d=0;d<f;d++)if(x(e[d])){c=e[d];break}a=this.m.bind(this,b,a);c?a(c):e.filter(w).forEach(a)}};
g.m=function(a,b,c){var e=c.name,f=e.replace(n,""),d;d=this.getBinder();if(p.test(f)){var m=f.replace(p,"");d=d.i.bind(a,u(m))}else q.test(f)?(m=f.replace(q,""),d=d.f.bind(a,m)):r.test(f)?(d=f.replace(r,""),d=this.l.bind(this,a,d,b)):d=this.a[f]&&"function"==typeof d[this.a[f]]?d[this.a[f]]:window.gwd&&window.gwd.binders&&"function"==typeof window.gwd.binders[f]?window.gwd.binders[f]:d.setAttribute.bind(a,f);e=a.getAttribute(e);b=(-1!==e.indexOf("|")?this.o.bind(this,b,e):this.g.bind(this,b,e)).call(a);
this.h&&"exit-override-url"==f&&a.setAttribute("exit-id",c.value.replace(/\./g,"_"));d.apply(a,[b])};
g.l=function(a,b,c,e){var f=a.parentNode;if(f){var d=a.cloneNode(!0);y(d);for(var m=[],k=0;e&&k<e.length;k++)m.push(d.cloneNode(!0));k={instances:m};d=document.createEvent("CustomEvent");d.initCustomEvent("gwdbindeachcloned",!0,!0,k);a.dispatchEvent(d);d=document.createComment("gwd-bind-each-placeholder");f.insertBefore(d,a);f.removeChild(a);A(a);if(e&&0!=e.length){for(var v,k=0;k<e.length;k++)c[b]=e[k],a=m[k],a.setAttribute("gwd-repeat-index",k),c.$index=k,v=Array.prototype.slice.call(a.querySelectorAll("*")),
this.bindData(c,v.concat(a)),f.insertBefore(a,d);delete c[b]}}};var A=function(a){a.setAttribute("gwd-bind-each-template","");Array.prototype.slice.call(a.querySelectorAll("*")).forEach(function(a){a.setAttribute("gwd-bind-each-template","")})};z.prototype.g=function(a,b){if(a){if(b){b=b.replace("[",".");b=b.replace("]","");var c=a;b.split(".").forEach(function(a){c&&(c=c[a])});return c}return a}return null};
z.prototype.o=function(a,b){if(b){b=b.split("|");var c=b.shift().trim();for(a=this.g(a,c);0<b.length;){var c=b.shift().trim(),c=c.split(" "),e=c.shift().trim();c.unshift(a);var f=this.getFormatter();a=this.b[e]&&"function"==typeof f[this.b[e]]?f[this.b[e]].apply(this,c):window.gwd&&window.gwd.formatters&&"function"==typeof window.gwd.formatters[e]?window.gwd.formatters[e].apply(this,c):a}}return a};z.prototype.attributeChangedCallback=null;document.registerElement("gwd-data-binder",{prototype:z.prototype});}()
